### PR TITLE
[WIP] UBX9 changes

### LINKED ISSUE #3: UBX-NAV-PVT has changed for the zed-f9p
The existing u8 version has a different length so a u9 version will be needed.
Screen Shot 2019-06-04 at 11 26 19 PM

### LINKED ISSUE #4: F9P Support
@arobenko 
Hi,
I tried adding the new ConfigItems as described in the [interface definition](https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf) but now I dont know how to make the different configuration items. I currently add them just as data but ideally I would like to define items for each item where the key is fixed and the data is constrained to the allowed values. What would be the most elegant way to do this via dsl?

[https://github.com/jowoeber/cc.ublox.commsdsl](https://github.com/jowoeber/cc.ublox.commsdsl)

### LINKED ISSUE #6: CfgMsg needs additional Ids for RCTM messages
Since UBXv9 there are more msgId especially for the CfgMsg to set RCTM Message Rate. 

[https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf#page=257&zoom=100,0,124](https://www.u-blox.com/sites/default/files/u-blox_ZED-F9P_InterfaceDescription_%28UBX-18010854%29.pdf#page=257&zoom=100,0,124)

In the coming days, i will be making a pull request to address these changes.

### PR DESCRIPTION
**Pull request by mathisloge**
This is work in progress.

Early pull request for better visibility

This closes #6, closes #4, closes #3

### CODE REVIEW

**Comment by mathisloge** [comment]
For the sake of completeness: 
There is a bug in UBX-CFG-PRT Message.
It was fixed inside this [commit](https://github.com/arobenko/cc.ublox.commsdsl/pull/7/commits/a3130a828bdea103b16d9b06218bed1970d29f0e#diff-64d0d8b4076446b7fb43e1f5a016fef6L100). here is the [reference](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29_Public.pdf#page=227&zoom=100,0,124)

The Port-Flags are not inside this, also the reserved2 bits are 8 bytes long

**Comment by arobenko** [comment]
Thanks for the report about CFG-PRT bug. Don't know how I missed it. It's USB variant, right?
I'll cherry-pick the fix and merge to master soon.

I also took a quick look at provided patches and here are a couple of comments.
Please avoid using hardcoded paths such as 
```
set(COMMS_INSTALL_DIR "C:/Users/mathi/source/libs/commsdsl/out/install/x86-Release/lib/")
```
Also I'd like to use separate branch, say u-blox9 for this work.
Sorry, at this moment I don't have much time to closely follow your work. Maybe it's a good idea to keep this work completely separate and only submit pull-request for review (or mail me to check the work in your repository) when it is complete.

**Comment by mathisloge** [comment]
Yes it is the CFG-PRT_USB Message.

My suggestion would be that we run this as a pull request and merge into a new branch at the end. I would leave this open, just to let others see that ubx9 is being worked on.

I will remove the hardcoded paths when im done ok? Visual Studio with cmake require them. I have to look where the settings are in it.

No problem because of the time. I'll probably need a little more, too.

**Comment by arobenko** [comment]
The pull request is not longer relevant.
Full support of ublox-9 receiver was introduced in the recent [v0.20](https://github.com/commschamp/cc.ublox.commsdsl/releases/tag/v0.20) release.

**Pull request closed without merging**
